#ifndef FILE_DEF_H
#define FILE_DEF_H

typedef enum {
    PROGRAM,
    DECLARATION,
    FUNCTION_DEFINITION,
    PARAMETERS,
    DECLARATORS,
    INIT_DECLARATORS,
    INIT_DECLARATOR,
    INITIALIZER,
    TYPE_SPECIFIER,
    TYPE_SPECIFIERS,
    STRUCT_OR_UNION,
    PLAIN_DECLARATION,
    DECLARATOR,
    PLAIN_DECLARATOR,
    STATEMENT,
    EXPRESSION_STATEMENT,
    COMPOUND_STATEMENT,
    SELECTION_STATEMENT,
    ITERATION_STATEMENT,
    JUMP_STATEMENT,
    EXPRESSION,
    ASSIGN_EXPRESSION,
    ASSIGN_OPERATOR,
    CONSTANT_EXPRESSION,
    LOGICAL_OR_EXPRESSION,
    LOGICAL_AND_EXPRESSION,
    INCLUSIVE_OR_EXPRESSION,
    EXCLUSIVE_OR_EXPRESSION,
    AND_EXPRESSION,
    EQUALITY_EXPRESSION,
    EQUALITY_OPERATOR,
    RELATIONAL_EXPERSSION,
    RELATIONAL_OPERATOR,
    SHIFT_EXPRESSION,
    SHIFT_OPERATOR,
    ADDITIVE_EXPRESSION,
    ADDITIVE_OPERATOR,
    MULTIPLICATIVE_EXPRESSION,
    MULTIPLICATIVE_OPERATOR,
    CAST_EXPRESSION,
    TYPE_NAME,
    UNARY_EXPRESSION,
    UNARY_OPERATOR,
    POSTFIX_EXPRESSION,
    POSTFIX,
    ARGUMENTS,
    PRIMARY_EXPRESSION,
    CONSTANT,
    IDENTIFIER,
    INTEGER_CONSTANT,
		DOUBLE_CONSTANT,
    CHARACTER_CONSTANT,
    STRING_CONSTANT,
    OPERATOR,
    KEYWORDS
} TreeNodeType;

typedef struct TreeNode {
    TreeNodeType type;
    char* data;
    int size, capacity;
    struct TreeNode** children;
    struct InfoNode* info;
} TreeNode;

#endif
